#!/bin/bash

#Colors

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # no color


#Init

echo -e "\n${RED}$USER${NC} ¿What command you want to execute?\n"

read -rp "Enter option: " command

echo -e "\n${BLUE}Executing: ${CYAN}${option}${NC}\n"

echo $command



#Times and execute commands

start_ns=$(date +%s%N)

eval "$option"

end_ns=$(date +%s%N)


#Calculate duration in nanoseconds

timed_ns=$((end_ns - start_ns))


#Extract parts

seconds=$((timed_ns / 1000000000))
milliseconds=$(( (timed_ns / 1000000) % 1000 ))
microseconds=$(( (timed_ns / 1000) % 1000 ))



#Show

echo -e "\n${GREEN}Execution time:${NC} ${seconds}s ${milliseconds}ms ${microseconds}μs"
