#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # no color


echo -e "\n${RED}$USER${NC} ¿What command you want to execute?\n"

read -rp "Enter option: " option

echo -e "\n${BLUE}Executing: ${CYAN}${option}${NC}\n"
echo $option
eval "$option"

start=$(date +%s)

sleep 0
end=$(date +%s)

duration=$((end - start))
echo -e "\n${GREEN}Execution time: ${NC}${duration} seconds\n"
